spring.datasource.url=jdbc:postgresql://postgres:5432/bidflow
spring.data.redis.host=redis
spring.cassandra.contact-points=cassandra-db:9042
spring.kafka.bootstrap-servers=kafka:9092
spring.minio.endpoint=http://minio:9000
