spring.application.name=bidflow
spring.jpa.hibernate.ddl-auto=validate

# Redis
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/bidflow
spring.datasource.username=bidflow
spring.datasource.password=bidflow

#Cassandra
spring.cassandra.contact-points=127.0.0.1:9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.keyspace-name=bidflow
spring.cassandra.schema-action=create_if_not_exists

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Producer Configs
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Consumer Configs
spring.kafka.consumer.group-id=bidflow-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
